### ISSUE TITLE
Scheduling  the at command in windows

### ISSUE THREAD

**Issue by steve55792** [t3rmin8tor/kodi-player-core-factory-install#1]
Hi, I just installed your program in windows and i was wondering how would a person schedule a recording for a later date in kodi with the at command like it is in Linux? I went back to windows because i wanna try your program with windows and kopdi, dont get me wrong linux is awesome too.

                                                                                                               steve

**Comment by NapoleonWils0n** [comment]
hi mate, windows does have an at command but its not the same as the linux version
so you cant use the windows at command you have to look at schtasks on windows which lets you schedule commands

but i coulnt get my head around schtasks syntax

you could try to figure out to use schtasks to schedule recordings yourself, 
the commands are much longer than at commands

it might be possible in the future to build some gui front to schtasks to schedule recordings
but for the moment id use linux and the at command to schedule recordings

**Comment by t3rmin8tor** [comment]
hi steve at the moment Rip-record is not capable of using the windows schtasks 

i am however working on a solution to this  hopefuly in the near future there will be a release of Rip-Record with a scheduler  the difficulty is getting the windows system to work seamlessly with bash

the basic command line syntax is 

schtasks /Create /SC DAILY / DATE / TIME /TN taskname /TR "'bash rip-record -f  00:01:00  videofile.txt 'C:\'"
the above command  tells the system to create a daily or a set date and time task with  TN being the name of the task (can be what ever you choose)  the TR tells the system which task it should run  in this case we want the system to run "bash rip-record  assuming you know how long you want to record its best to set the time with -t in rip-record itself  (failsafe) you dont want schtasks to forget to terminate the command  so i would tell rip-record to stop at the end of the recording

i hope this has given you the answers you require

**Comment by steve55792** [comment]
Thank you for the info, it'll take me a few trials and error to learn that stuff. For instance i would like to record the CBS News at 5pm Wednesday the 12/28/2016, How would we set it up with bash rip-record in schtasks?

**Comment by t3rmin8tor** [comment]
hi steve 

the  command would be  schtasks /create /Date /time  /TN CBS_NEWS  /TR "bash rip-record -f 00:01:00 (name of video file) 'C:'"


that is the command  however as stated  there is an issue getting bash to run correctly with schtasks 

i would suggest  that  putting the bash command  in a bat file   and telling schtasks to run the bat file  would possibly be more reliable

**Comment by NapoleonWils0n** [comment]
Hi Steve 

The command should be -t and not -f

the command would be schtasks /create /Date /time /TN CBS_NEWS /TR "bash rip-record -t 00:01:00 (name of video file) 'C:'"

**Comment by t3rmin8tor** [comment]
thanks @NapoleonWils0n  for correcting my error

**Comment by steve55792** [comment]
execuse me for being a blonde moment but what you are saying is that put the command you and napoleonWilson showed me and put it as a bat file and use the task scheduler? Thank you NapoleonWilson for the help, I appreciate this.

**Comment by NapoleonWils0n** [comment]
Hi steve

im no windows expert, so this is just a guess

## try putting this in a bat file

you might need to specify the full path to the text file in the bat file
eg: replace videourl.txt with the full path to the text file


```
bash rip-record -t 00:01:00 videourl.txt
```

* then the schtask command might be something like this
* replace path-to-bat-file with the actual path to the bat file

```
schtasks /create /Date /time /TN CBS_NEWS /TR "path-to-bat-file 'C:'"
```

as i say thats just a guess on my part

we are just working on getting the windows installer working,
and fixing email sign ups on the site

**Comment by t3rmin8tor** [comment]
i can confirm  that schtasks /create /Date /time /TN CBS_NEWS /TR "path-to-bat-file 'C:'"
 is the correct syntax 

and that the bat file  should indeed contain the command 

bash rip-record -t 00:01:00 videourl.txt

**Comment by steve55792** [comment]
Okay here is what I got for the schtasks: schtasks /create /12/28/16 /5:00pm /TN CBS_NEWS /TR "C:\Users\Steve\Desktop 'C:'" and the bat file is of course on the desktop, or should I have the bat file location written after the last 'C:" not before?

**Comment by NapoleonWils0n** [comment]
Hi Steve

think you need the name of the bat file as well
replace batfile.bat with the name of your batfile and see if that works

```
schtasks /create /12/28/16 /5:00pm /TN CBS_NEWS /TR "C:\Users\Steve\Desktop\batfile.bat 'C:'" 
```

**Comment by steve55792** [comment]
After typing schtasks /create /12/28/16 /5:00pm /TN CBS_NEWS /TR "C:\Users\Steve\Desktop\batfile.bat 'C:'"  I got this error:  Invalid argument option 12/28/16. Type "Schtasks/create/?" for usage.  Maybe t3rmin8tor would know.

**Comment by NapoleonWils0n** [comment]
Hi Mate

found this howtogeek article about schtasks, dont know if that helps

http://www.howtogeek.com/51236/how-to-create-modify-and-delete-scheduled-tasks-from-the-command-line/

**Comment by t3rmin8tor** [comment]
hi steve   

 the syntax is schtasks /create /SD 12/28/16  /ST 5:00pm /TN CBS_NEWS /TR "C:\Users\Steve\Desktop\batfile.bat 'C:'"

**Comment by steve55792** [comment]
It says Mandatory option 'sc' is missing from the syntax

**Comment by t3rmin8tor** [comment]
sorry steve  my mistake  that should have been /SC 12/28/16

**Comment by steve55792** [comment]
Now it says invalid schedule type specified.  I have typed:  schtasks /create /SC 12/28/16 /ST 5:00pm /TN CBS_NEWS /TR "C:\Users\Steve\Desktop\Cbs.bat 'C:'"

**Comment by t3rmin8tor** [comment]
hi steve try  

schtasks /create /SC ONCE /SD 12/28/16 /ST 17:00 /TN CBS_NEWS /TR "C:\Users\Steve\Desktop\Cbs.bat 'C:'"

please note  that the commands are  experimental and still in development  there is no guarrantee that they will work ........or  that  even if schtasks accepts the perameters  that bash will accept  the commands

- i have corrected the  /ST 5:00pm  the correct use is   /ST 17:00

**Comment by steve55792** [comment]
i tried it and the outcome is:  Type "SCHTASKS /Create /?" for usage 
also it had a invalid argument/option- 'CBS_News/TR'.  I know it all experimental and there's no guarrantee that itll work, that's okay, I thought give it  a shot and see if itll work or not. Thanks for helping and I know your busy with this experiment. I appreciate it.

**Comment by t3rmin8tor** [comment]
hi steve  sorry i cant help any more  than i have
this is a valid function that needs to be addressed

be assured this  issue is an important development step and as soon as  a solution is found  it will be built into one of the beta releases  

ill let you know asap of further progress  on this issue

**Comment by t3rmin8tor** [comment]
hi steve i think  i have a solution 

schtasks /create /SC ONCE /TN "CBS_NEWS" /TR C:\Users\Steve\Desktop\Cbs.bat /ST 17:00 /DU 0000:59 /K


be aware  that the 0000:59  is  = 59 mins

**Comment by steve55792** [comment]
It created the task in the scheduler and it started but it did not make the video(.mkv) file.

**Comment by steve55792** [comment]
For the bat file i got: bash rip-record -t 00:05:00 http://usaiptv.ddns.net:9090/load/c5f07d7d9d81/9.m3u8
if that helps any?

**Comment by NapoleonWils0n** [comment]
hi steve 

that command is wrong the url goes before -t

**Comment by steve55792** [comment]
Sweeeeet , it works, thank you NapoleonWilson & t3rmin8tor for all the help, now we know it the schedule of later time for show & others will work in windows.

**Comment by steve55792** [comment]
for future recordings, just leave everything the same except the minutes/hours to record and the bat file? And for 2 hours = 0000:2:00

**Comment by steve55792** [comment]
what does the K  at the end stand for? Is it always gonna be K?

**Comment by t3rmin8tor** [comment]
hi steve  the /K tells schtasks  to  Kill the task at the end of the  event

yes  if  the  only  change is  the /ST    and /DU   perameters  those are  the only  changes needed 


for  reference  
 if you  wanted  to auto  record  the same stream  every day  
 change  the /SC once perameter to /SC Daily

weekly  would be 
/SC weekly   /MO  1-7     

/MO   is a modifier    1-7   are  the days in numbers 

/MO   could be set  as  /MO  1,3,5,7        this  would tell  schtasks  to  run on  1 mon  3 weds 5 fri 7 sun

**Comment by steve55792** [comment]
Wow, thanks t3rmin8tor for the information. Is there a website that has information like this, so i wont keep bugging you and NapoleonWilson all the time?

**Comment by t3rmin8tor** [comment]
hi steve   there isn't  a reliable  source  that  qualifies as a guide  there are pages that  ask for help with using schtask  and from my experience  the responces are not exact solutions  merely "have you tried this"  suggestions 

i will however be putting together a guide for schtask commands and syntax with accurate instructions and example  command templates

**Comment by steve55792** [comment]
Oh okay
