### ISSUE TITLE
V 2.2 problems

### ISSUE THREAD

**Issue by DJDubya** [t3rmin8tor/kodi-player-core-factory-install#10]
I am running Kodi under a freshly installed version of Windows7-64bit on a sand-box pc.

Yesterday I ran rip-record-install-v2.2 and it appeared to install successfully (except for the desktop icons. However the play or record functions under the y-context menu in Kodi do not work.

The rip-play bash script when run from a command window reports "line 74: ffplay: command not found".
The rip-record bash script when run from a command window reports "line 97: ffmpeg: command not found".

I know next to nothing about bash but is it possible that the scripts do not recognize/understand the Windows PATH environment variable?

Further thoughts/comments.

1. The addresses in the properties of you MPV and VLC desktop icons are incorrect.

Correct addresses for MPV on my config are:
	Target:   %ProgramFiles(x86)%\Rip-Record\Git\bin\mpv.exe
        Start in: %ProgramFiles(x86)%\Rip-Record\Git\bin

Correct addresses for VLC on my config are:
	Target:   %ProgramFiles(x86)%\Rip-Record\Git\bin\vlc.exe
        Start in: %ProgramFiles(x86)%\Rip-Record\Git\bin

2. I found that the http download of the installer was much much faster than torrent download.  I cancelled the torrent download after 20 minutes because it was so slow.

3. Your install is not "Windows certified" and does not appear to update the Windows register file. Therefore I don't know of any requirement for the your files to be be installed in the Program Files (86) folder on PCs running 64 bit versions of Windows. The main thing in those circumstances is to get the PATH set up correctly.

**Comment by onknight** [comment]
For me in did not install the files correctly   I'd go back to older version
