### ISSUE TITLE
Can't get anything to work.

### ISSUE THREAD

**Issue by refriedfood** [t3rmin8tor/kodi-player-core-factory-install#14]
I run windows 7 x64, have kodi-17.6-Krypton-x86 installed and rip-record-install-v2.2. I receive the options upon right clicking the stream (as hitting keys while the stream is playing does nothing), to save the url, play with my media players, etc. But, none of them save or even open in an external player.

I don't know what other information to provide that you might need, all I know is it doesn't work. I'm not a novice user, so information you ask for I can give you without effort. I even tried using a proxy scanner to grab urls through the data being streamed but they all forwarded to dead pages or temp pages that the file url could not be extracted from or even shown.

Any help in this matter would be great. All I really want to do is grab the source files from the server for later use without having to record (webrip-like) using a program like OBS, etc. as it captures the screen and its pauses.

Thanks.

**Comment by t3rmin8tor** [comment]
hi refriedfood thanks for raising the issue 

rip-record is now depreciated and has been replaced with 
<a href= "https://github.com/t3rmin8tor/pilfer-installer/releases/download/1.4/pilfer-1.4-install-32bit.exe">pilfer 1.4 32bit official release</a> works on both 32 and 64 bit systems

i advise  that you completeley uninstall Rip-Record and switch to the new software 
the pilfer repo is at 

<a href="https://github.com/t3rmin8tor/pilfer-installer">pilfer-installer</a>

be sure to install software in this order 

1 install pilfer 1.4 32bit official release 
2 install Pilfer-Gui-update-1.5
3 install pilfer-Gui-1.6
4 install pilfer upgrade v2.0 this release is a beta upgrade for existing users of version 1.6 only

hope this  helps  let me know if you need  any more assistance

**Comment by refriedfood** [comment]
Thanks for your response. How do I remove this from my root directory? I need it on another drive, will it have adverse effects if I move the directory?

**Comment by t3rmin8tor** [comment]
hi refriedfood pilfer is not designed to  run on any other drive but the root drive eg c:\pilfer

however  if you let me know which drive you require the application to run on in relation to your kodi install folder  i can look at 

1 building a custom install for your system
or 
2 write a custom configuration for your system

i appreciate  the feedback as it really does help development
 and agree that the installer needs to be more dynamic

**Comment by refriedfood** [comment]
I suppose it really doesn't matter as by default (on win7) it saves from ffmpeg to your desktop, but that's still your main OS drive. Since I'm no expert in python and what you're using to call back these scripts to a location, I can't say whether or not it would simply be a matter of having an installer that let you choose a location to install the directory (as rip-record allowed).

It does the job in kodi by use of Y and ffmpeg. Though, the pilfer command is not usable and no executable exists in Windows\System32 in order to run commands out of a prompt alone and by saving a url through kodi (as per your video tutorial).

My personal concern and request for a location choice has to do with drive space. If there is a simple way to specify where I want to save the file, that'll work, but I just figured killing two birds with one stone would do the trick-- choose install dir-- choose download dir.

**Comment by t3rmin8tor** [comment]
hi refried 
so my understanding of you request is to 
1 be able to move the saved video-url.txt files to a location outside of the root folder (eg an external/alternative drive)
2 move recordeded .mkv files to an alternative location similar to  that in 1

or
3  have the option to configure  pilfer to set recording locations and save locations for video.txt files 

it isnt possible to change the install folder location but it is possible to set  save locations 

i appreciate  your feedback let me know which solution would be more useful

**Comment by refriedfood** [comment]
Yeah, basically. I think you may be over complicating it. But, it's just the ability to specify a save directory outside of command prompt use (meaning when you hit "record" it will record to which drive you _specified_ in a file or when you install or through a GUI, etc) for videos.

i.e. I want all mkv/video/srt/files, etc to save to \path\I've\specified in a file or GUI somewhere instead of the default (desktop).

This is convenient because for me, the other features do not work. Pilfer doesn't run as a command in cmd and there is no batch or com file in system32 to run pilfer, so I cannot save a text file and use prompt commands to grab the video files and save them to where I want. The only thing that works for me (on win7/kodi 17.6) is the in program menu under (Y key) inside kodi. This means I'm stuck with the default save directory.

The other suggestion had to do with where you installed pilfer itself, for me it's my root drive C:\pilfer
This isn't a big deal, I just thought it'd be nice to be able to make that portable or specify where to install during its installation, like D:\utilities\pilfer

If it's too much of a hassle to do any of this don't worry about it. I'm fine using the inapp menu and glad you've made what you've made. I used to grab using a proxy/packet reader and grab the url, but pilfer with ffmpeg can bypass SSL obfuscation urls, which is fantastic. I have no complaints.

**Comment by t3rmin8tor** [comment]
hi refried  have you 
1opened the pilfer-gui
2 selected config tab
3 clicked configure pilfer 

without  these steps the pilfer install is incomplete

**Comment by refriedfood** [comment]
Yep. A few times, uninstalled reinstalled, just gave up it. I even tried installing just 1.4, running the config, and it didn't work. I tried several combinations. I think the issue with that has to do with below win10. In 7, anything you put in windows\system32 can be run from any location using the command prompt, not SysWOW64. Again, though, it isn't a big deal if I can't use the prompt.

*If you'd like me to test something since I run win7 64, I'd be willing to help.
