### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by thorpey70** [t3rmin8tor/kodi-player-core-factory-install#4]
Hi guys,

Been trying to get this to work for days now. I followed the video exactly but I just cannot get this to work at all.

The installer runs but it doesn't appear to install correctly. Rip-Record gets a directory on C:\Program Files (x86)\Rip-Record but it has no effect on Kodi. I cant save a video url or play it in mpv.

I copied the playercorefactory to the user data file, as well as %appdata% kodi userdata folder but I still cant get it to work.

I wiped the computer clean so it had nothing on it before I downloaded, installed and ran Kodi for the first time. Then ran the installer and still no joy.

Any ideas to help me get this working?

Thanks for your time.

**Comment by NapoleonWils0n** [comment]
Hi Mate

it was a bug with the installer which has been fixed now
new version of the installer on the rip-record download page

could you try the new version and see if it fixes the issue for you
new version may work on windows preview but no guarantee

i did reply to your coment on youtube as well

**Comment by PlaceboPRS** [comment]
(I think I was the windows 10 preview / youtube guy you were thinking of) :)

I tried the new installer (filename has remained the same right?) and nothing has changed sadly, same warning in the log (I'd mentioned it on the youtube comments):

08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(save video url): no such player: save video url
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(mpv): no such player: mpv
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(play): no such player: play
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(vlc): no such player: vlc
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(external player): no such player: external player
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(video stats): no such player: video stats
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(record): no such player: record
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(record 30 mins): no such player: record 30 mins
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(record 1 hour): no such player: record 1 hour
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(record 2 hours): no such player: record 2 hours
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(record 3 hours): no such player: record 3 hours
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(stream): no such player: stream
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(stream 2 hours): no such player: stream 2 hours
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(stream 3 hours): no such player: stream 3 hours
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(ssh record): no such player: ssh record
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(ssh record 30 mins): no such player: ssh record 30 mins
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(stream 1 hour): no such player: stream 1 hour
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(ssh record 2 hours): no such player: ssh record 2 hours
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(ssh record 3 hours): no such player: ssh record 3 hours
08:04:05.272 T:4320 WARNING: CPlayerCoreFactory::GetPlayer(save audio url): no such player: save audio url

And when I right click / play as nothing happens (other than a small window popping up and instantly closing).

**Comment by thorpey70** [comment]
Thanks for replying Nepoleon,

I re-downloaded the .exe and ran it as admin this morning but still no joy.

**Comment by cwh060** [comment]
I had a similar problem with version 1.8 last weekend.  I had to run the exe without admin privileges then it worked. After installation I checked all the familiar install spots, Kodi userdata, Environmental path's, rip-record bin folder. It worked. 
Don't forget to un-install rip-record if trying again.
To test, press Y when playback and try to create a .txt url file.

**Comment by PlaceboPRS** [comment]
I got it fixed just now thanks to Jack in the youtube comments,  **C:%HOMEPATH%\git\kodi-playercorefactory\bash-scripts-windows;** was completely missing from my paths after using the installer, added it manually to the bottom of the system paths and everything now works, currently doing a test record from Viaplay which was my whole purpose for it in the first place! :)

**Comment by cwh060** [comment]
Good stuff, it's a great little set of programs. I've been using for quite sometime on my Windows machines.

**Comment by thorpey70** [comment]
Thanks for all your help guys,

Following the advice above i checked my %HOMEPATH% folder and copied in the Git/kodi-playercorefactory folder there. Also added it to the end of my system path. IT WORKED!! Spent the evening recording with no issues. I turned it off and went to bed 

I turned it on again this morning and it doesnt seem to want to work again. Ive checked the system path and the %HOMEPATH% folder to make sure the changes i made yesterday ate still there, which they were. 

Anyone have any idea what may have changed to stop this from working?

Thanks again for all your help so far. When it works, its brillient software!!

**Comment by cwh060** [comment]
Windows has a problem remembering the environmental path. You will have to open the advanced settings and click each item listed in the Path as if editing. Don't have to change anything just highlight the field and place a space then backspace. 

I know it's odd, but that's windows. I've not had to do this with the latest verison, but then I don't turn off my machines very often.

**Comment by thorpey70** [comment]
Damn Windows trickery!

Will give this a go this evening and report back. 

Thanks for your help!!

**Comment by thorpey70** [comment]
After many weeks of trying to get this to work, i have finally managed it.

Thanks for this awesome software Nepoleon ans thanks for all your help getting this to work.
