### ISSUE TITLE
Version 2.2

### ISSUE THREAD

**Issue by cwh060** [t3rmin8tor/kodi-player-core-factory-install#8]
Uninstalled v1.8 and all components. Installed 2.2.

mpv, vlc do not launch, I see they are installed.
pressing Y then=> record comes up with errors, ffmpeg commands can't process or something ...sorry, it flashes in cmd window then closes right away. Then says, cannot record here. Almost like the directory to store the file does not exists. 

Pressing Y and saving the URL file, does work and a txt file is created on the desktop.

Is there a log file somewhere?

**Comment by cwh060** [comment]
Program drops a shortcut on the desktop for VLC, however it's pointing to the incorrect file path. (C:\Program Files (x86)\Rip-Record\bin\vlc.exe)

It should be C:\Program Files (x86)\Rip-Record\Git\bin\vlc.exe not a big deal just fixed it.

I checked the system variables, no entry is made. I added one, but no luck fixing above.

**Comment by cwh060** [comment]
Uninstalled version 2.2 and went to 2.0. All shortcuts are created properly. The Save Video-Url still works. The record function does work after some errors https://www.screencast.com/t/4SrptINdO6 . Tried to create the folder rip-record in the directory specified, windows does not allow this creation as the bash scripts are named the same.

**Comment by gs1512** [comment]
Similar issues with 2.2 on Windows 7-64.  Paths in VLC and MPV shortcuts are wrong. Corrected these manually but no change to functionality.  Hope this helps.
GS1512
